### ISSUE TITLE
点击提交注册按钮无反应，页面上方一直显示LICENSE ERROR

### ISSUE THREAD

**Issue by git-lxb** [OnceDoc/OnceAir#6]
设置管理员用户界面，点击提交按钮无反应，页面上方一直显示LICENSE ERROR

**Comment by newghost** [comment]
在先接电源，然后等待一待时间后再接网线，会比较容易重现这个BUG。
原因是，网卡长时间并未初始化，造成 License 装载失败，在这种情况下，可**重新热插拔电源一次**。

我们已经在 build.2374 之后的版本做了修改，如果局域网连接一直无法建立的话会持续尝试初始化，10分钟。
